package web

import (
	"encoding/json"
	"fmt"
	"net/http"
	"sort"
	"strings"
	"time"

	"gorm.io/gorm"

	"scrutineer/internal/db"
)

// scanReport serves the scan's results as a downloadable markdown file.
// Findings-kind scans reuse the per-finding renderer from repo_report.go;
// other kinds are walked into markdown tables, falling back to a fenced
// JSON block for shapes we can't tabulate.
func (s *Server) scanReport(w http.ResponseWriter, r *http.Request) {
	var scan db.Scan
	if err := s.DB.Preload("Repository").First(&scan, r.PathValue("id")).Error; err != nil {
		http.NotFound(w, r)
		return
	}

	// Skill is fetched separately: Scan.SkillID is nullable and Preload on
	// a nullable FK is fiddly across GORM versions. A missing skill row is
	// non-fatal; we lose OutputKind dispatch and fall back to raw.
	var skill *db.Skill
	if scan.SkillID != nil {
		var sk db.Skill
		if err := s.DB.First(&sk, *scan.SkillID).Error; err == nil {
			skill = &sk
		}
	}

	body := renderScanReport(s.DB, &scan, skill)

	filename := fmt.Sprintf("scrutineer-%s-scan-%d-%s-%s.md",
		sanitiseFilename(scan.Repository.Name),
		scan.ID,
		sanitiseFilename(firstNonEmpty(scan.SkillName, scan.Kind, "scan")),
		time.Now().UTC().Format("20060102"))
	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)
	_, _ = w.Write([]byte(body))
}

func renderScanReport(gdb *gorm.DB, scan *db.Scan, skill *db.Skill) string {
	var b strings.Builder
	writeScanReportHeader(&b, scan)
	writeScanReportMetadata(&b, scan, skill)

	kind := ""
	if skill != nil {
		kind = skill.OutputKind
	}
	switch kind {
	case "findings":
		writeScanReportFindings(&b, gdb, scan)
	default:
		writeScanReportFreeform(&b, scan, kind)
	}
	return b.String()
}

func writeScanReportHeader(b *strings.Builder, scan *db.Scan) {
	title := firstNonEmpty(scan.SkillName, scan.Kind, "scan")
	fmt.Fprintf(b, "# %s — scan #%d\n\n", title, scan.ID)
	repoName := firstNonEmpty(scan.Repository.FullName, scan.Repository.Name, scan.Repository.URL)
	if scan.Repository.URL != "" {
		fmt.Fprintf(b, "From [%s](%s).\n\n", repoName, scan.Repository.URL)
	} else if repoName != "" {
		fmt.Fprintf(b, "From %s.\n\n", repoName)
	}
	fmt.Fprintf(b, "Generated by [scrutineer](https://github.com/alpha-omega-security/scrutineer) at %s UTC.\n\n",
		time.Now().UTC().Format("2006-01-02 15:04"))
	fmt.Fprintf(b, "---\n\n")
}

func writeScanReportMetadata(b *strings.Builder, scan *db.Scan, skill *db.Skill) {
	fmt.Fprintf(b, "## Scan metadata\n\n")
	rows := [][2]string{
		{"Scan ID", fmt.Sprintf("%d", scan.ID)},
		{"Repository", firstNonEmpty(scan.Repository.FullName, scan.Repository.Name)},
		{"Skill", scan.SkillName},
		{"Status", string(scan.Status)},
		{"Model", scan.Model},
	}
	if skill != nil && skill.OutputKind != "" {
		rows = append(rows, [2]string{"Output kind", skill.OutputKind})
	}
	if scan.Commit != "" {
		rows = append(rows, [2]string{"Commit", "`" + shortCommit(scan.Commit) + "`"})
	}
	if scan.Ref != "" {
		rows = append(rows, [2]string{"Ref", scan.Ref})
	}
	if scan.StartedAt != nil {
		rows = append(rows, [2]string{"Started", scan.StartedAt.UTC().Format(time.RFC3339)})
	}
	if scan.FinishedAt != nil {
		rows = append(rows, [2]string{"Finished", scan.FinishedAt.UTC().Format(time.RFC3339)})
		if scan.StartedAt != nil {
			rows = append(rows, [2]string{"Duration", scan.FinishedAt.Sub(*scan.StartedAt).Round(time.Second).String()})
		}
	}
	if scan.Turns > 0 {
		rows = append(rows, [2]string{"Turns", fmt.Sprintf("%d", scan.Turns)})
	}
	if scan.CostUSD > 0 {
		rows = append(rows, [2]string{"Cost", fmt.Sprintf("$%.4f", scan.CostUSD)})
	}
	if scan.FindingsCount > 0 {
		rows = append(rows, [2]string{"Findings reported", fmt.Sprintf("%d", scan.FindingsCount)})
	}

	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		if r[1] == "" {
			continue
		}
		fmt.Fprintf(b, "| %s | %s |\n", r[0], r[1])
	}
	b.WriteString("\n")

	if strings.TrimSpace(scan.Error) != "" {
		fmt.Fprintf(b, "### Error\n\n```\n%s\n```\n\n", strings.TrimSpace(scan.Error))
	}
}

func writeScanReportFindings(b *strings.Builder, gdb *gorm.DB, scan *db.Scan) {
	// OR last_seen_scan_id and scan_id so re-observed findings still
	// surface here; older scans whose findings have since moved to a
	// later scan inherit that scan's location data (the DB doesn't
	// snapshot per-scan state). scan_show.html's Preload("Findings")
	// undercounts the same way; worth a separate issue.
	var findings []db.Finding
	gdb.Where("last_seen_scan_id = ? OR scan_id = ?", scan.ID, scan.ID).
		Order("severity, id").Find(&findings)
	fmt.Fprintf(b, "## Findings\n\n")
	if len(findings) == 0 {
		fmt.Fprintf(b, "No findings recorded by this scan.\n\n")
		return
	}

	fmt.Fprintf(b, "%d finding(s).\n\n", len(findings))
	fmt.Fprintf(b, "| # | Severity | Status | Title | Location |\n|---|---|---|---|---|\n")
	for _, f := range findings {
		fmt.Fprintf(b, "| %d | %s | %s | %s | `%s` |\n",
			f.ID, f.Severity, f.Status, escapeMD(f.Title), f.Location)
	}
	b.WriteString("\n")

	for _, f := range findings {
		writeReportFinding(b, gdb, f, scan)
	}
}

// writeScanReportFreeform turns report.json into markdown: top-level
// scalars become a metadata table, arrays-of-objects each get their own
// section. CycloneDX SBOMs get a tuned heading. Anything we can't
// tabulate falls back to a fenced JSON block.
func writeScanReportFreeform(b *strings.Builder, scan *db.Scan, kind string) {
	raw := strings.TrimSpace(scan.Report)
	if raw == "" {
		fmt.Fprintf(b, "## Report\n\nNo report produced.\n\n")
		return
	}

	var top map[string]any
	if err := json.Unmarshal([]byte(raw), &top); err != nil {
		// Not a JSON object (bare array, plain text, malformed JSON): ship as-is.
		writeScanReportJSONBlock(b, raw, kind)
		return
	}

	fmt.Fprintf(b, "## %s\n\n", freeformHeading(top, kind))

	scalars, arrays := classifyTopLevel(top)
	wroteAnything := writeScalarTable(b, top, scalars)
	for _, k := range arrays {
		items, _ := top[k].([]any)
		writeArraySection(b, k, items)
		wroteAnything = true
	}

	if !wroteAnything {
		writeScanReportJSONBlock(b, raw, kind)
	}
}

func writeScanReportJSONBlock(b *strings.Builder, raw, kind string) {
	label := "Raw report"
	if kind != "" {
		label = fmt.Sprintf("Raw report (%s)", kind)
	}
	fmt.Fprintf(b, "## %s\n\n", label)
	fmt.Fprintf(b, "```json\n%s\n```\n\n", prettyJSON(raw))
}

func freeformHeading(top map[string]any, kind string) string {
	if format, _ := top["bomFormat"].(string); format == "CycloneDX" {
		spec, _ := top["specVersion"].(string)
		if spec != "" {
			return fmt.Sprintf("SBOM (CycloneDX %s)", spec)
		}
		return "SBOM (CycloneDX)"
	}
	if kind != "" {
		return "Report (" + kind + ")"
	}
	return "Report"
}

// classifyTopLevel splits keys into scalar-shaped (single-row metadata)
// and array-of-objects (their own section). Arrays of scalars and nested
// objects fall in the scalar bucket since they fit a single cell.
func classifyTopLevel(top map[string]any) (scalars, arrays []string) {
	keys := make([]string, 0, len(top))
	for k := range top {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if arr, ok := top[k].([]any); ok && len(arr) > 0 {
			if _, ok := arr[0].(map[string]any); ok {
				arrays = append(arrays, k)
				continue
			}
		}
		scalars = append(scalars, k)
	}
	return scalars, arrays
}

func writeScalarTable(b *strings.Builder, top map[string]any, keys []string) bool {
	rows := make([][2]string, 0, len(keys))
	for _, k := range keys {
		v := freeformCellString(top[k])
		if v == "" {
			continue
		}
		rows = append(rows, [2]string{k, v})
	}
	if len(rows) == 0 {
		return false
	}
	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| %s | %s |\n", escapeMD(r[0]), escapeMD(r[1]))
	}
	b.WriteString("\n")
	return true
}

func writeArraySection(b *strings.Builder, key string, items []any) {
	fmt.Fprintf(b, "### %s (%d)\n\n", key, len(items))
	if len(items) == 0 {
		b.WriteString("None.\n\n")
		return
	}
	cols := pickFreeformColumns(items)
	if len(cols) == 0 {
		// Nothing tabulatable: emit a JSON block so data isn't lost.
		buf, _ := json.MarshalIndent(items, "", "  ")
		fmt.Fprintf(b, "```json\n%s\n```\n\n", string(buf))
		return
	}
	b.WriteString("|")
	for _, c := range cols {
		fmt.Fprintf(b, " %s |", escapeMD(c))
	}
	b.WriteString("\n|")
	for range cols {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	for _, item := range items {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		b.WriteString("|")
		for _, c := range cols {
			fmt.Fprintf(b, " %s |", escapeMD(freeformCellString(m[c])))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

// pickFreeformColumns samples up to 50 items and returns up to 6
// commonly-present scalar keys. Preferred names (name, version, ...)
// come first when present so SBOMs and package lists render predictably.
func pickFreeformColumns(items []any) []string {
	const sampleSize = 50
	const maxCols = 6

	counts := map[string]int{}
	seen := 0
	for i, item := range items {
		if i >= sampleSize {
			break
		}
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		seen++
		for k, v := range m {
			if isFreeformCellValue(v) {
				counts[k]++
			}
		}
	}
	if seen == 0 {
		return nil
	}

	preferred := []string{
		"name", "version", "type", "ecosystem",
		"license", "licenses", "purl",
		"severity", "cwe", "cve", "cvss", "rating",
		"title", "summary", "description",
		"location", "url", "id", "login", "email",
	}
	used := map[string]bool{}
	out := make([]string, 0, maxCols)
	for _, k := range preferred {
		if counts[k] > 0 {
			out = append(out, k)
			used[k] = true
			if len(out) >= maxCols {
				return out
			}
		}
	}

	type kn struct {
		k string
		n int
	}
	rest := make([]kn, 0, len(counts))
	for k, n := range counts {
		if !used[k] {
			rest = append(rest, kn{k, n})
		}
	}
	sort.Slice(rest, func(i, j int) bool {
		if rest[i].n != rest[j].n {
			return rest[i].n > rest[j].n
		}
		return rest[i].k < rest[j].k
	})
	for _, r := range rest {
		if len(out) >= maxCols {
			break
		}
		out = append(out, r.k)
	}
	return out
}

// isFreeformCellValue reports whether v fits in a single markdown cell:
// scalars and short lists of scalars or {id,name}-style objects.
func isFreeformCellValue(v any) bool {
	const maxInlineArrayLen = 5
	switch x := v.(type) {
	case nil, bool, float64, string:
		return true
	case []any:
		if len(x) > maxInlineArrayLen {
			return false
		}
		for _, e := range x {
			switch ev := e.(type) {
			case string, float64, bool, nil:
				continue
			case map[string]any:
				if _, ok := ev["id"]; ok {
					continue
				}
				if _, ok := ev["name"]; ok {
					continue
				}
				return false
			default:
				return false
			}
		}
		return true
	default:
		return false
	}
}

// freeformCellString collapses a JSON value to a single-line cell.
// Leaf scalars delegate to scalarString (jsontree.go) for parity with
// the HTML Data tab; license arrays like [{id: "MIT"}] collapse to "MIT";
// deep nested objects return "" so writeScalarTable drops their row.
func freeformCellString(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case []any:
		const cap = 3
		parts := make([]string, 0, cap)
		for _, e := range x {
			var s string
			switch ev := e.(type) {
			case map[string]any:
				if id, ok := ev["id"].(string); ok {
					s = id
				} else if name, ok := ev["name"].(string); ok {
					s = name
				}
			default:
				s = scalarString(ev)
			}
			if s != "" {
				parts = append(parts, s)
			}
			if len(parts) >= cap && len(x) > cap {
				parts = append(parts, fmt.Sprintf("(+%d more)", len(x)-cap))
				break
			}
		}
		return strings.Join(parts, ", ")
	case map[string]any:
		if name, ok := x["name"].(string); ok {
			return name
		}
		if id, ok := x["id"].(string); ok {
			return id
		}
		return ""
	default:
		return scalarString(v)
	}
}
